# Generated by Django 4.2.5 on 2023-12-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Miembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=30)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="Equipo")),
                ("experiencia", models.TextField(max_length=30)),
                ("pais", models.TextField(max_length=30)),
                ("epecializacion", models.TextField(max_length=30)),
                ("empresas", models.TextField(max_length=50)),
            ],
        ),
    ]
