# Generated by Django 4.2.5 on 2023-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_miembro_empresas_alter_miembro_epecializacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="miembro",
            name="apellido",
            field=models.TextField(max_length=30, null=True),
        ),
    ]
