# Generated by Django 4.2.5 on 2023-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_miembro_apellido"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasoDeExito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=30)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="Casos de exito"
                    ),
                ),
                ("situacion", models.TextField(max_length=250)),
                ("servicio", models.TextField(max_length=100)),
                ("resultados", models.TextField(max_length=250)),
            ],
        ),
    ]
