# Generated by Django 4.2.5 on 2023-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_casodeexito"),
    ]

    operations = [
        migrations.AddField(
            model_name="casodeexito",
            name="ubicacion",
            field=models.TextField(max_length=50, null=True),
        ),
    ]
