# Generated by Django 4.2.5 on 2023-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_casodeexito_resultados_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion1", models.CharField(max_length=30)),
                ("descripcion2", models.CharField(max_length=30)),
                ("descripcion3", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="casodeexito",
            name="nombre",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="miembro",
            name="apellido",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="miembro",
            name="nombre",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="miembro",
            name="pais",
            field=models.CharField(max_length=30),
        ),
    ]
